import { create } from 'zustand';

export const subjects = [
  {
    id: 'dsa',
    name: 'DSA',
    branch: 'Logic Branch',
    icon: 'Network',
    mastery: 72,
    xp: 4820,
    activeTopic: 'Recursion',
    color: '#22d3ee',
    topics: [
      { id: 'arrays', name: 'Arrays', mastery: 94, weak: false, eta: '18m' },
      { id: 'linked-lists', name: 'Linked Lists', mastery: 81, weak: false, eta: '26m' },
      { id: 'trees', name: 'Trees', mastery: 48, weak: true, eta: '54m' },
      { id: 'graphs', name: 'Graphs', mastery: 24, weak: true, eta: '1h 20m' },
    ],
  },
  {
    id: 'aiml',
    name: 'AI/ML',
    branch: 'Neural Branch',
    icon: 'Brain',
    mastery: 64,
    xp: 3210,
    activeTopic: 'Model Evaluation',
    color: '#c084fc',
    topics: [
      { id: 'linear-regression', name: 'Linear Regression', mastery: 77, weak: false, eta: '30m' },
      { id: 'classification', name: 'Classification', mastery: 62, weak: false, eta: '45m' },
      { id: 'overfitting', name: 'Overfitting', mastery: 39, weak: true, eta: '28m' },
    ],
  },
  {
    id: 'math',
    name: 'Mathematics',
    branch: 'Pattern Branch',
    icon: 'Sigma',
    mastery: 78,
    xp: 3880,
    activeTopic: 'Probability',
    color: '#34d399',
    topics: [
      { id: 'calculus', name: 'Calculus', mastery: 86, weak: false, eta: '25m' },
      { id: 'probability', name: 'Probability', mastery: 71, weak: false, eta: '34m' },
      { id: 'matrices', name: 'Matrices', mastery: 53, weak: true, eta: '42m' },
    ],
  },
  {
    id: 'cloud',
    name: 'Cloud',
    branch: 'Sky Branch',
    icon: 'Cloud',
    mastery: 46,
    xp: 1720,
    activeTopic: 'Load Balancing',
    color: '#60a5fa',
    topics: [
      { id: 'compute', name: 'Compute', mastery: 58, weak: false, eta: '22m' },
      { id: 'storage', name: 'Storage', mastery: 44, weak: true, eta: '36m' },
      { id: 'networking', name: 'Networking', mastery: 35, weak: true, eta: '52m' },
    ],
  },
  {
    id: 'physics',
    name: 'Physics',
    branch: 'Energy Branch',
    icon: 'Atom',
    mastery: 57,
    xp: 2340,
    activeTopic: 'Waves',
    color: '#38bdf8',
    topics: [
      { id: 'motion', name: 'Motion', mastery: 73, weak: false, eta: '20m' },
      { id: 'waves', name: 'Waves', mastery: 55, weak: true, eta: '40m' },
      { id: 'electricity', name: 'Electricity', mastery: 43, weak: true, eta: '50m' },
    ],
  },
  {
    id: 'cybersecurity',
    name: 'Cybersecurity',
    branch: 'Shield Branch',
    icon: 'Shield',
    mastery: 51,
    xp: 1990,
    activeTopic: 'Threat Models',
    color: '#f472b6',
    topics: [
      { id: 'network-security', name: 'Network Security', mastery: 60, weak: false, eta: '32m' },
      { id: 'crypto', name: 'Cryptography', mastery: 42, weak: true, eta: '58m' },
      { id: 'web-security', name: 'Web Security', mastery: 49, weak: true, eta: '44m' },
    ],
  },
];

const treeStages = ['Seed', 'Sprout', 'Young Tree', 'Knowledge Tree', 'Elite Tree'];

export const useLearningOSStore = create((set, get) => ({
  user: {
    name: 'Kasturi',
    xp: 18420,
    streak: 12,
    rank: 'Strategist',
    language: 'English',
  },
  focus: {
    active: false,
    mode: 'Pomodoro',
    secondsRemaining: 1480,
    score: 91,
    concentration: 'Deep Work',
    sessionsToday: 3,
    masteryEta: '46m',
  },
  tree: {
    stage: 4,
    studyHours: 126,
    quizzesCompleted: 83,
    revisionStrength: 78,
    consistency: 86,
    focusSessions: 42,
    glow: 88,
  },
  subjects,
  activeSubjectId: 'dsa',
  activeTopic: { id: 'recursion', name: 'Recursion', subjectId: 'dsa', mastery: 72 },
  accessibility: {
    blindMode: false,
    highContrast: false,
    voiceNavigation: true,
    scalableText: true,
  },
  getTreeStage: () => treeStages[Math.min(get().tree.stage, treeStages.length - 1)],
  setActiveSubject: (activeSubjectId) => set({ activeSubjectId }),
  openTopic: (topic, subjectId = get().activeSubjectId) => set({ activeTopic: { ...topic, subjectId } }),
  startFocus: () => set((state) => ({ focus: { ...state.focus, active: true } })),
  stopFocus: () => set((state) => ({ focus: { ...state.focus, active: false } })),
  setFocusMode: (mode) => set((state) => ({ focus: { ...state.focus, mode } })),
  toggleAccessibility: (key) => set((state) => ({
    accessibility: { ...state.accessibility, [key]: !state.accessibility[key] },
  })),
}));
